name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install wasm-tools
      run: dotnet workload install wasm-tools 
    - name: Restore projects
      run: dotnet restore
    - name: Build projects
      run: dotnet build /warnaserror --configuration Release --no-restore
    - name: Upload WASM AppBundle artifact
      uses: actions/upload-artifact@v3
      with:
        name: invaders-app-bundle
        path: ./SpaceInvaders.Web/bin/Release/net7.0/browser-wasm/AppBundle/
