name: Deploy browser-wasm to Netlify

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: Download AppBundle
    uses: actions/download-artifact@v3
    with:
      name: invaders-app-bundle
    - name: Netlify Deploy
      uses: jsmrcaga/action-netlify-deploy@v1.8.2
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}